### ISSUE TITLE
Elixir change compile path

### ISSUE THREAD

**Issue by PragTob** [arboricity/openfaas-templates#2]
:wave: 

I met Alex Ellis a while ago at GOTO Berlin and I might have a solution for one of the problems with the elixir template: Because it expects things to be in the lib directory I believe files are copied around.

You can just adjust the paths elixir considers for compilation. You can see an example here: https://github.com/bencheeorg/benchee/blob/master/mix.exs#L11

Basically within the `def project` you'd want to give it `elixirc_paths: ["your_non_lib_dir"]`

Cheers,
Tobi

**Comment by dokie** [comment]
>:wave:  ...

@PragTob Thanks. Alex mentioned this to me too. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
